Iter5
gdyunin/metricol pull request #5
Opened 2024-11-25 14:53 UTC by gdyunin

2024-11-29 15:28 UTC, gdyunin commented on .github/workflows/golangci-lint.yml
> +name: golangci-lint
Есть локальный golangci-lint. Линтер в workflows планирую настроить позже

2024-11-29 15:33 UTC, gdyunin commented on .github/workflows/golangci-lint.yml
> +name: golangci-lint
Аутпут локального golangci-lint. Ругается только на дублирование в тестах. Мне показалось, что можно оставить и так, но nolint юзать не стал на всякий
```
{
  "Issues": [
    {
      "FromLinter": "dupl",
      "Text": "129-148 lines are duplicate of `internal\\metrics\\gauge_test.go:147-166`",
      "Severity": "error",
      "SourceLines": [
        "\tfor _, tt := range tests {",
        "\t\tt.Run(tt.name, func(t *testing.T) {",
        "\t\t\tc := \u0026Counter{",
        "\t\t\t\tname:  \"test_counter\",",
        "\t\t\t\tvalue: tt.initialValue,",
        "\t\t\t}",
        "",
        "\t\t\tif tt.fetcher != nil {",
        "\t\t\t\treturnedG := c.SetFetcherAndReturn(tt.fetcher)",
        "\t\t\t\trequire.Equal(t, c, returnedG)",
        "\t\t\t}",
        "",
        "\t\t\terr := c.Update()",
        "\t\t\tif err != nil {",
        "\t\t\t\trequire.True(t, tt.expectError)",
        "\t\t\t\trequire.Equal(t, ErrorFetcherNotSet, err.Error())",
        "\t\t\t}",
        "\t\t\trequire.Equal(t, tt.expectedValue, c.value)",
        "\t\t})",
        "\t}"
      ],
      "Replacement": null,
      "LineRange": {
        "From": 129,
        "To": 148
      },
      "Pos": {
        "Filename": "internal\\metrics\\counter_test.go",
        "Offset": 0,
        "Line": 129,
        "Column": 0
      },
      "ExpectNoLint": false,
      "ExpectedNoLintLinter": ""
    },
    {
      "FromLinter": "dupl",
      "Text": "10-49 lines are duplicate of `internal\\metrics\\factory_test.go:51-90`",
      "Severity": "error",
      "SourceLines": [
        "func TestNewGauge(t *testing.T) {",
        "\ttests := []struct {",
        "\t\tname          string",
        "\t\tinputName     string",
        "\t\tinputValue    float64",
        "\t\texpectedName  string",
        "\t\texpectedValue float64",
        "\t}{",
        "\t\t{",
        "\t\t\tname:          \"create simple gauge\",",
        "\t\t\tinputName:     \"cpu_usage\",",
        "\t\t\tinputValue:    75.5,",
        "\t\t\texpectedName:  \"cpu_usage\",",
        "\t\t\texpectedValue: 75.5,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:          \"create gauge with zero value\",",
        "\t\t\tinputName:     \"memory_usage\",",
        "\t\t\tinputValue:    0.0,",
        "\t\t\texpectedName:  \"memory_usage\",",
        "\t\t\texpectedValue: 0.0,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:          \"create gauge with negative value\",",
        "\t\t\tinputName:     \"temperature\",",
        "\t\t\tinputValue:    -20.3,",
        "\t\t\texpectedName:  \"temperature\",",
        "\t\t\texpectedValue: -20.3,",
        "\t\t},",
        "\t}",
        "",
        "\tfor _, tt := range tests {",
        "\t\tt.Run(tt.name, func(t *testing.T) {",
        "\t\t\tgauge := NewGauge(tt.inputName, tt.inputValue)",
        "\t\t\trequire.Equal(t, tt.expectedName, gauge.Name())",
        "\t\t\trequire.Equal(t, tt.expectedValue, gauge.Value())",
        "\t\t\trequire.Equal(t, MetricTypeGauge, gauge.Type())",
        "\t\t})",
        "\t}",
        "}"
      ],
      "Replacement": null,
      "LineRange": {
        "From": 10,
        "To": 49
      },
      "Pos": {
        "Filename": "internal\\metrics\\factory_test.go",
        "Offset": 0,
        "Line": 10,
        "Column": 0
      },
      "ExpectNoLint": false,
      "ExpectedNoLintLinter": ""
    },
    {
      "FromLinter": "dupl",
      "Text": "51-90 lines are duplicate of `internal\\metrics\\factory_test.go:10-49`",
      "Severity": "error",
      "SourceLines": [
        "func TestNewCounter(t *testing.T) {",
        "\ttests := []struct {",
        "\t\tname          string",
        "\t\tinputName     string",
        "\t\tinputValue    int64",
        "\t\texpectedName  string",
        "\t\texpectedValue int64",
        "\t}{",
        "\t\t{",
        "\t\t\tname:          \"create simple counter\",",
        "\t\t\tinputName:     \"requests\",",
        "\t\t\tinputValue:    100,",
        "\t\t\texpectedName:  \"requests\",",
        "\t\t\texpectedValue: 100,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:          \"create counter with zero value\",",
        "\t\t\tinputName:     \"errors\",",
        "\t\t\tinputValue:    0,",
        "\t\t\texpectedName:  \"errors\",",
        "\t\t\texpectedValue: 0,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:          \"create counter with negative value\",",
        "\t\t\tinputName:     \"negative_counter\",",
        "\t\t\tinputValue:    -50,",
        "\t\t\texpectedName:  \"negative_counter\",",
        "\t\t\texpectedValue: -50,",
        "\t\t},",
        "\t}",
        "",
        "\tfor _, tt := range tests {",
        "\t\tt.Run(tt.name, func(t *testing.T) {",
        "\t\t\tcounter := NewCounter(tt.inputName, tt.inputValue)",
        "\t\t\trequire.Equal(t, tt.expectedName, counter.Name())",
        "\t\t\trequire.Equal(t, tt.expectedValue, counter.Value())",
        "\t\t\trequire.Equal(t, MetricTypeCounter, counter.Type())",
        "\t\t})",
        "\t}",
        "}"
      ],
      "Replacement": null,
      "LineRange": {
        "From": 51,
        "To": 90
      },
      "Pos": {
        "Filename": "internal\\metrics\\factory_test.go",
        "Offset": 0,
        "Line": 51,
        "Column": 0
      },
      "ExpectNoLint": false,
      "ExpectedNoLintLinter": ""
    },
    {
      "FromLinter": "dupl",
      "Text": "39-80 lines are duplicate of `internal\\metrics\\gauge_test.go:104-145`",
      "Severity": "error",
      "SourceLines": [
        "\ttests := []struct {",
        "\t\tname          string",
        "\t\tinitialValue  float64",
        "\t\tfetcher       func() float64",
        "\t\texpectedValue float64",
        "\t\texpectError   bool",
        "\t}{",
        "\t\t{",
        "\t\t\tname:         \"success set simple fetcher and update\",",
        "\t\t\tinitialValue: 0.0,",
        "\t\t\tfetcher: func() float64 {",
        "\t\t\t\treturn 42.0",
        "\t\t\t},",
        "\t\t\texpectedValue: 42.0,",
        "\t\t\texpectError:   false,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:         \"success set fetcher that return negative number and update\",",
        "\t\t\tinitialValue: 10.0,",
        "\t\t\tfetcher: func() float64 {",
        "\t\t\t\treturn -7.5",
        "\t\t\t},",
        "\t\t\texpectedValue: -7.5,",
        "\t\t\texpectError:   false,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:         \"success set fetcher that return big number and update\",",
        "\t\t\tinitialValue: 100.0,",
        "\t\t\tfetcher: func() float64 {",
        "\t\t\t\treturn 1e9",
        "\t\t\t},",
        "\t\t\texpectedValue: 1e9,",
        "\t\t\texpectError:   false,",
        "\t\t},",
        "\t\t{",
        "\t\t\tname:          \"try set empty fetcher and update\",",
        "\t\t\tinitialValue:  25.0,",
        "\t\t\tfetcher:       nil,",
        "\t\t\texpectedValue: 25.0,",
        "\t\t\texpectError:   true,",
        "\t\t},",
        "\t}"
      ],
      "Replacement": null,
      "LineRange": {
        "From": 39,
        "To": 80
      },
      "Pos": {
        "Filename": "internal\\metrics\\gauge_test.go",
        "Offset": 0,
        "Line": 39,
        "Column": 0
      },
      "ExpectNoLint": false,
      "ExpectedNoLintLinter": ""
    },
    {
      "FromLinter": "dupl",
      "Text": "104-145 lines are duplicate of `internal\\metrics\\gauge_test.go:39-80`",
      "Severity": "error",
      "SourceLines": [
        "\ttests := []struct {",
        "\t\tname          string",
        "\t\tinitialValue  float64",
        "\t\tfetcher       func() float64",
        "\t\texpectedValue float64",
        "\t\texpectError   bool",
        "\t}{",
        "\t\t{",
        "\t\t\tname:         \"success set simple fetcher and update\",",
        "\t\t\tinitialValue: 0.0,",
        "\t\t\tfetcher: func() float64 {",
        "\t\t\t\treturn 42.0", [...]

2024-11-29 18:53 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-11-29 18:53 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
Сейчас этот Action запускает логгер со стандартной конфигурацией. Она детектирует довольно мало проблем. Это то, что ты хотел сделать ?

Если нет, то неплохой вариант конфигурации можно забрать отсюда: https://github.com/s-shpak/praktikum-golangci-lint

2024-11-29 18:53 UTC, s-shpak commented on cmd/agent/config.go
> +	_ = env.Parse(&cfg)
Я бы не игнорировал ошибку, а возвращал ее наверх и завершал процесс. Если пользователь ожидает, что конфигурация подтянется из переменных окружения, а этого не происходит из-за ошибки, то ее игнор приведет к неожиданному для пользователя поведению агента

2024-11-29 18:53 UTC, s-shpak commented on cmd/agent/main.go
> +func main() {
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-11-29 18:53 UTC, s-shpak commented on internal/agent/fetch/metrics_fetrcher.go
> +			fmt.Printf("metric %s update fail: %s", mm.Name(), err.Error())
Не используй пакет `fmt`, вместо него используй `log`. В дальнейшем, как ты правильно заметил, мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-11-29 18:53 UTC, s-shpak commented on internal/agent/fetch/types.go
> +type Fetcher interface {
В Go интерфейсы принято объявлять рядом с местом их использования: в одном пакете и, чаще всего, рядом с функцией/методом, которые их используют. Существуют исключения, но это не тот случай

2024-11-29 18:53 UTC, s-shpak commented on internal/agent/send/metrics_sender.go
> +			fmt.Println(err.Error())
Посмотри вебинар -- там мы обсуждали работу с ошибками.

Здесь ее можно прокинуть выше и залогировать уже на уровне цикла отправки

2024-11-29 18:53 UTC, s-shpak commented on internal/metrics/counter.go
> +func (c *Counter) Name() string {
В Go не принято использовать геттеры/сеттеры без дополнительной логики. Можно просто сделать поля экспортируемыми

2024-11-29 18:53 UTC, s-shpak commented on internal/metrics/counter.go
> +	return MetricTypeCounter
Если тебе надо проверить тип объекта, то ты можешь сделать это напрямую с объектом

2024-11-29 18:53 UTC, s-shpak commented on internal/metrics/counter.go
> +		return nil, errors.New(ErrorParseMetricValue)
В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где

2024-11-29 18:53 UTC, s-shpak commented on internal/metrics/types.go
> +	ErrorParseMetricValue  = "error parse metric value"
1. Если объявляешь ошибку таким образом, то это более идиоматично делать так:

```suggestion
	ErrParseMetricValue  = errors.New("error parse metric value")
```

2. А зачем тебе вообще определять эту ошибку ? Она нигде не проверяется, зачем ее "типизировать" вместо простого `fmt.Errorf` ?

2024-11-29 18:53 UTC, s-shpak commented on internal/server/handlers/main_page.go
> +const mainPageTemplate = `<!DOCTYPE html>
Я рекомендую использовать вот этот пакет здесь: https://pkg.go.dev/html/template

2024-11-29 18:53 UTC, s-shpak commented on internal/server/handlers/metric_get.go
> +			switch err.Error() {
Ошибки следует проверять при помощи `errors.Is`/`errors.As`

2024-11-29 18:53 UTC, s-shpak commented on internal/server/handlers/metric_post.go
> +			http.Error(w, err.Error(), http.StatusInternalServerError)
Штатные ошибки (т.е. те ошибки, которые приводят к ответу клиенту с кодом 4**) не нужно логировать: они произошли "по вине" клиента и будут только замусоривать лог. А вот ошибки 5** нужно логировать обязательно

В случае нештатной ошибки, нельзя посылать детали о ней пользователю, т.к. это угроза безопасности приложения.

2024-11-29 18:53 UTC, s-shpak commented on internal/server/storage/store.go
> +		value = fmt.Sprintf("%g", v)
Для конвертации строк в числа и обратно используй пакет `strconv`. Он:
- позволяет более точно указывать параметры конвертации
- просто работает быстрее `fmt.Sprintf` из-за того, что не использует рефлексию

2024-11-29 18:53 UTC, s-shpak commented on internal/metrics/counter.go
> +	c.value += c.fetcher()
Хорошая попытка :) Но согласно ТЗ первого инкремента требуется сделать так, чтобы сервер прибавлял значение `Counter` к хранимому. Поменяй эту логику так, чтобы она удовлетворяла ТЗ, пожалуйста

2024-11-30 16:14 UTC, gdyunin commented on cmd/agent/config.go
> +	_ = env.Parse(&cfg)
Теперь этим будет заниматься функция parseEnv, которая пытается получить енвы и если получила, то сразу возвращаем конфиг, если не получила, то сама залогирует и мы пойдем к флагам командной строки

Обрабатываем ошибку сразу на уровне parseEnv, потому что по ТЗ отсутствие енвов не блокирует запуск приложения, а лишь говорит, что мы должны перейти к следующему приоритету (флагам командной строки)

2024-11-30 16:23 UTC, gdyunin commented on cmd/agent/main.go
> +func main() {
Согласен. Конфиги переехали в свою директорию в internal

2024-11-30 16:32 UTC, gdyunin commented on cmd/agent/main.go
> +func main() {
Ниже в коде есть вызов fetcher.AddMetrics для добавления в него метрик. Имхо это относится к "и настройка компонентов", т.к. непосредственно эти метрики и будут собираться. Прикольно сделать отдельный универсальный функционал для управления подключенными метриками, но кажется, что противоречит YAGNI (?), т.к. в ТЗ не оговаривалось, что необходимо предоставлять гибкий интерфейс для подключения метрик из разных мест или разными способами

2024-11-30 16:33 UTC, gdyunin commented on cmd/server/main.go
> +func main() {
```config.ParseServerConfig()```
Конфиг переехал в директорию config в internal

2024-11-30 16:48 UTC, gdyunin commented on internal/agent/fetch/types.go
> +type Fetcher interface {
Переедет в metrics_fetcher (который будет переименован в просто fetcher.go)

2024-11-30 16:50 UTC, gdyunin commented on internal/agent/fetch/metrics_fetrcher.go
> +			fmt.Printf("metric %s update fail: %s", mm.Name(), err.Error())
Поменял

2024-11-30 16:52 UTC, gdyunin commented on internal/agent/fetch/metrics_fetrcher.go
> +			fmt.Printf("metric %s update fail: %s", mm.Name(), err.Error())
Вверх по стеку не передаем, т.к. ошибка не считается фатальной и вполне может быть обработана (в данном случае просто залогирована) на этом этапе и дальше влиять не должна

2024-11-30 17:01 UTC, gdyunin commented on internal/metrics/counter.go
> +func (c *Counter) Name() string {
+

2024-11-30 17:02 UTC, gdyunin commented on internal/metrics/counter.go
> +	return MetricTypeCounter
В первичной версии в том числе на этом методе был завязан интерфейс. Сейчас можно без него, выпиливаю

2024-11-30 17:06 UTC, gdyunin commented on internal/metrics/counter.go
> +func (c *Counter) SetFetcherAndReturn(f func() int64) *Counter {
@s-shpak помоги тут, нормально вообще так делать? Просто хотелось бы иметь метод, позволяющий установить фетчер и сразу получить обратно структуру, а просто "set_fetcher" по названию не дает понимание того, что структура будет возвращена

2024-11-30 17:08 UTC, gdyunin commented on internal/metrics/counter.go
> +	c.value += c.fetcher()
Ой, это была грубая ошибка, тут оно и не должно себя так вести :D Тут оно просто должно апдейтиться на то, что вернула функция-сборщик. Поправил

2024-11-30 17:14 UTC, gdyunin commented on internal/metrics/counter.go
> +func newCounterFromStrings(name, value string) (Metric, error) {
Возвращаем интерфейс, а не структуру. Как будто плохо, но по сути это не экспортируемый метод, который необходим только для корректной работы фабрики по строительству метрик (метрика = интерфейс Metric), поэтому тут выбрано такое решение. Сама фабрика в соседнем файле "factory.go"

2024-12-01 09:06 UTC, gdyunin commented on internal/server/handlers/main_page.go
> +const mainPageTemplate = `<!DOCTYPE html>
+

2024-12-01 11:16 UTC, gdyunin commented on internal/server/handlers/metric_get.go
> +			switch err.Error() {
\+

2024-12-01 11:34 UTC, gdyunin commented on internal/server/handlers/metric_post.go
> +			http.Error(w, err.Error(), http.StatusInternalServerError)
\+

2024-12-01 11:39 UTC, gdyunin commented on internal/server/storage/store.go
> +		value = fmt.Sprintf("%g", v)
\+

2024-12-01 12:14 UTC, gdyunin commented on .github/workflows/golangci-lint.yml
Забрал)

2024-12-01 12:16 UTC, gdyunin commented on internal/agent/send/metrics_sender.go
> +			fmt.Println(err.Error())
+

2024-12-01 12:20 UTC, gdyunin commented on internal/metrics/counter.go
> +		return nil, errors.New(ErrorParseMetricValue)
\+

2024-12-01 12:27 UTC, gdyunin commented on internal/metrics/types.go
> +	ErrorParseMetricValue  = "error parse metric value"
1. +
2. Согласен, тоже +

2024-12-01 18:01 UTC, gdyunin commented on .github/workflows/golangci-lint.yml
Настроил нормально линтер в Actions

2024-12-01 18:02 UTC, gdyunin commented
Документация частично написана ChatGPT

2024-12-04 09:40 UTC, s-shpak commented on cmd/agent/config.go
> +	_ = env.Parse(&cfg)
ТЗ обсуждает только приоритет флагов, но не поведение в случае проблемы с переданной конфигурацией.

Представим сценарий: ты запускаешь приложение, передавай туда флаг -timeout=5s. Проблема в том, что конфигурация ожидает численное зачение, потому не может распарсить строку "5s". Ошибка лоигруется, но ты не замечаешь ее, потому что логов много. После чего приложение запускается с дефолтным таймаутом в 10 минут.

Кажется, что это не то поведение, которого хотел бы добиться пользователь

2024-12-04 09:43 UTC, s-shpak commented on cmd/agent/main.go
> +func main() {
Все равно кода пока много. Лучше инкапсулируй создание и конфигурацию фетчера и т.п. в `internal`

2024-12-04 09:45 UTC, s-shpak commented on internal/agent/fetch/types.go
> +type Fetcher interface {
Нет, пока это неправильно. Интерфейсы объявляются там, где они исползуются, а не там, где объявлены реализующие их структуры. Существуют исключения, но это не тот случай

2024-12-04 12:27 UTC, gdyunin commented on cmd/agent/main.go
> +func main() {
Инкапсулировал в `internal` 👍

2024-12-04 16:08 UTC, gdyunin commented on internal/agent/fetch/types.go
> +type Fetcher interface {
Ааа, туплю, извини. Понял, перенес (и также для Sender поступил)

2024-12-04 20:40 UTC, s-shpak requested changes

2024-12-05 14:17 UTC, gdyunin commented on cmd/agent/main.go
> +			return 1
Я дурак 🫏 Читал ТЗ несколько раз и постоянно думал, что при отправке на сервер мы должны на стороне сервера понимать, сколько раз мы получили метрики (т.е. агент всегда по идее шлёт единицу)

Сейчас наконец дошло, что мы должны на агенте понимать, сколько раз мы получали метрики и это же кол-во отсылать на сервер.

Поправлю 👍

2024-12-05 14:31 UTC, gdyunin commented on cmd/agent/main.go
> +			return 1
Поправил. Добавил переменную-счётчик, а метрику реализовал замыканием, которое захватывает переменную и при каждом вызове инкрементирует её и потом возвращает. Теперь получается, что при каждом вызове ` func (m *MetricsFetcher) Fetch() error` счётчик вырастает на 1, т.е. каждый опрос метрик инкрементирует счётчик и при `func (m *MetricsSender) Send() error` на сервер улетает суммарное кол-во сборов метрик.

```go
func setDefaultMetrics(fetcher Fetcher) {
	...
	var pollCounter int64 = 0
        ...
        fetcher.AddMetrics(
        ...
            metrics.NewCounter("PollCount", 0).SetFetcherAndReturn(func() int64 {
			pollCounter++
			return pollCounter
	    }),
        )
}
```

2024-12-06 14:25 UTC, s-shpak commented on cmd/agent/main.go
> +			return 1
Все почти правильно, но есть еще одна проблема:

Счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-12-06 14:25 UTC, s-shpak requested changes
См. последний комментарий

2024-12-06 20:10 UTC, gdyunin commented on cmd/agent/main.go
> +			return 1
Подумал. Кажется, что в таком контексте можно сказать, что метрика хочет подписаться на событие отправки. То есть, можно сказать, что метрика должна наблюдать за событием отправки и при возникновении события применять какую-то логику. В данном ключе можно попробовать реализовать паттерн наблюдателя, в котором Sender будет нотифаером, а метрика обсёрвером

2024-12-06 20:13 UTC, gdyunin commented on cmd/agent/main.go
> +			return 1
А точнее, не хочется учить абсолютно все метрики подписываться на что-то, зачем пытаться имплементировать интерфейс обсёрвера всем метрикам, если они им пользоваться не будут, а будет только PollCounter. Имплементируем интерфейс обсёрвера прямо в функцию-сборщик для этой конкретной метрики

2024-12-07 11:53 UTC, gdyunin commented on cmd/agent/main.go
> +			return 1
Подумал. Кажется, что в этом случае мы хотели бы подписаться и следить за сендером и по сигналу от него что-то делать. Мне показалось, что это очень похоже на паттерн наблюдателя, поэтому через него и попытался реализовать

Создал наблюдателя, добавил ему экшн на сброс pollCounter и подписал на сендера
```go
...
senderObserver := &SenderObserver{}
senderObserver.addAction(func() {
	pollCounter = 0
})
a.sender.RegisterObserver(senderObserver)
...
```

У сендера реализовал соответствующие методы

Протестировал, работает как ожидается: после отправки данных на сервер сендер уведомляет наблюдателя, который в свою очередь сбрасывает pollCounter в 0

В будущем можно также будет переиспользовать, если другие метрики или какие-то сущности после отправки на сервер тоже захотят что-то делать

_Накидал тудушек на написание тестов, рефакт и на защиту pollCounter от возможной гонки данных (не уверен, что она возникнет, но как будто может возникнуть). Я бы оставил это как техдолг и сделал бы в начале нового спринта, если ты не против_

2024-12-08 22:22 UTC, s-shpak commented on cmd/agent/main.go
> +			return 1
В принципе, это неплохой подход к разделению ответственности, круто.

Про техдолг -- да, без проблем

2024-12-08 22:22 UTC, s-shpak approved these changes

2024-12-09 06:36 UTC, merged